### PR TITLE
Feature/glide 3 

### PR DESCRIPTION
**Pull request by MarkusAJacobsen**
Due to the limitations of Firebase Admin SDK does this only contain admin endpoints for creating, updating, fetching an deleting users

### CODE REVIEW

**Comment by Horcon** [comment]
All 4 files are significantly lacking in comments, Variable names like "u" and "uu" and other instances of one-letter variable names are not acceptable, the only exception being iterators in for loops etc. Noticed 2 instances of copy-pasted strings, "no uId provided" (main.go) and "could not contact firebase" (userHandler.go). The first triggers a code smell on sonar rules (that I just made admittely). Consider making them string consts, especially if we get more functionality in the backend that could trigger these error messages. Have not yet tried running the code itself.

**Review by Horcon — CHANGES_REQUESTED** [review]
Comments, string consts

**Comment by MarkusAJacobsen** [comment]
> All 4 files are significantly lacking in comments, Variable names like "u" and "uu" and other instances of one-letter variable names are not acceptable, the only exception being iterators in for loops etc. Noticed 2 instances of copy-pasted strings, "no uId provided" (main.go) and "could not contact firebase" (userHandler.go). The first triggers a code smell on sonar rules (that I just made admittely). Consider making them string consts, especially if we get more functionality in the backend that could trigger these error messages. Have not yet tried running the code itself.

Taken from golang's code review docuent: 
image

Short variable names are encouraged by the go devs, and that is why you see it so often in go code. I do agree with the comments and consts though

**Comment by Horcon** [comment]
I can agree with that if that's what they recommend, but then the purpose of those variables should be commented, similar to Javadoc or something.

**Comment by MarkusAJacobsen** [comment]
It's like, the devs recommend it, and sometimes I understand. Due to the nature of golang, but some do need more descriptive name. I'll go through the suggested changes now

**Comment by MarkusAJacobsen** [comment]
Commit: https://github.com/GlidingTracks/gt-backend/pull/2/commits/4085ba585aaa146e23757439b41f3c81059d4bbb cleaned up user returns, and sticked with logging only the error, for now. Also, we should not include comments in methods unless there are some especially wonky logic.

This commit also changes to named returns, so beware

**Comment by Horcon** [comment]
Now it looks much better. Minor details that sonar will keep track of in the future, but otherwise I find this good to go. Something to consider for the future, right now both running code and test code are in the same directory. Maybe we should separate these and put all test files in /test.

**Review by Horcon — APPROVED** [review]

**Pull request merged**
